### ISSUE TITLE
Can coilmq be "embedded" into a Python application?

### ISSUE THREAD

**Issue by sjlongland** [hozn/coilmq#27]
Hi,

I'm working on a `aiohttp`-based server application and have a need to perform real-time messaging between clients over HTTP/WebSockets.  While I have tried to DIY a solution, I'm not happy with the results… and I think I'd be better served using an existing framework with a standardised protocol.

I'd like to avoid running yet another daemon, just for the sake of having messaging.  It'd also simplfy the interface into the server application, since it can directly inject messages into the STOMP queues and monitor requests rather than having to do this through a client interface itself.

Is it possible to embed `coilmq` into another Python application?

**Comment by hozn** [comment]
Yes.  It's a library; it's really designed primarily to be run inside another application.

This was more of a proof-of-concept, however, to play with multi-threading in python, and hasn't been kept up-to-date as python has evolved.  I'd use it as a set of ideas, rather than something to integrate in a modern app.  If you are looking for a toolbox for building your own broker, maybe consider ZeroMQ too.
